### ISSUE TITLE
Error in this line ```r = algorithms.eaSimple(population, toolbox, cxpb = 0.4, mutpb = 0.1, ngen = num_generations, verbose = False)``` while implementation in colab.

### ISSUE THREAD

**Issue by aman-17** [aqibsaeed/Genetic-Algorithm-RNN#4]
/usr/local/lib/python3.7/dist-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMax' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/usr/local/lib/python3.7/dist-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)

Window Size:  56 , Num of Units:  7
Epoch 1/5
---------------------------------------------------------------------------
UnimplementedError                        Traceback (most recent call last)
<ipython-input-20-f2943874fe0b> in <module>()
     19 
     20 population = toolbox.population(n = population_size)
---> 21 r = algorithms.eaSimple(population, toolbox, cxpb = 0.4, mutpb = 0.1, ngen = num_generations, verbose = False)

8 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

UnimplementedError:  Cast string to float is not supported
	 [[node model_3/Cast (defined at <ipython-input-19-137a48f9e0b0>:32) ]] [Op:__inference_train_function_4464]

Function call stack:
train_function****

**Comment by aqibsaeed** [comment]
Please try to debug the problem by reading error log instead of copy pasting, this is the error:

` RuntimeWarning: A class named 'FitnessMax' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.`

Restart your notebook and call/run the cell in notebook **only once**, hopefully, this will resolve this problem.
